const ownedtracesList = [
  "A Thousand Gates",
  "Beneath The Deception",
  "Bewitching Night",
  "Blood Ruvia - Secret",
  "Codename Diversity",
  "Deadline",
  "Elegy At Dusk",
  "Emptiness",
  "Hustle And Bustle",
  "Into A Paper Crane",
  "Muscle Building",
  "Name Of The Line",
  "Remaining Friends",
  "Smoke Of Chaos",
  "Testing Limits",
  "To The New World",
  "Dawn",
  "Get Well Soon",
  "Hello, Visier",
  "Illusion Of Flowers",
  "In-Between Time",
  "Karma",
  "Lawful Cage",
  "Lightchaser",
  "Night In The City",
  "Oldtown Nightsky",
  "RPG",
  "Where The Star Fell",
  "Wonders Of Technology",
  "Born From Ashes",
  "Happy Hours",
  "Hidden Blade",
  "Hiding In The City",
  "Home",
  "Moments Before Nightfall",
  "Passage",
  "Racing Night",
  "Silent Yesterday",
  "Sirius",
  "Starlit Memories",
  "Sweet Thoughts",
  "Unexpected Encounter",
  "Wet Path",
  "Blows? Bonds?",
  "Divination",
  "Filing",
  "Growth",
  "Invisible Mirror",
  "Old Alley",
  "One More Step",
  "Reunion",
  "The Sun Never Sets",
  "The Unexpected",
  "The Weight Of Life",
  "Warm Winter",
  "Where The Sun Is",
  "Wish In The Rain",
  "Amidst The Crowd",
  "Behind The Curtains",
  "Blending In",
  "Company",
  "Curiosity Of A Hailinian",
  "Dream Of Cherry Blossoms",
  "Dusk Radiance",
  "Early Market",
  "Into The Fantasy",
  "Lectures On Arcane Theories",
  "Light Of Knowledge",
  "Managing Marks",
  "Moonlit Confession",
  "Sweet Dreams",
];

export default ownedtracesList;
